### ISSUE TITLE
HTTP-Header "Cache-Control:no-store, no-cache, must-revalidate"

### ISSUE THREAD

**Issue by Hermsi1337** [Florent73/send-pdf-for-contact-form-7#2]
Hey m8,

as soon as I activate your plugin "Send PDF for Contact Form 7" it prevents my Varnish or W3 Total Cache from caching.
I investigated it further and found out, that somehow your plugin adds no-cache header to http-response.

Could you tell me why this is the case and how to prevent this? Otherwise I won't get my Varnish working properly.^^

Thank you!

**HTTP-Header without plugin:**
```
HTTP/1.1 200 OK
Date: Mon, 20 Nov 2017 08:35:55 GMT
Server: Apache
Link: <http://example.com/wp-json/>; rel="https://api.w.org/"
Upgrade: h2,h2c
Connection: Upgrade, Keep-Alive
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 18339
Keep-Alive: timeout=5, max=100
Content-Type: text/html; charset=UTF-8
```

**HTTP-Header with plugin:**
```
HTTP/1.1 200 OK
Date: Mon, 20 Nov 2017 08:34:56 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Link: <http://example.com/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 18339
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```

**How to reproduce:**
Simply set up a default WordPress with "Send PDF for Contact Form 7" plugin and load frontend.

**Comment by f4w-pwharton** [comment]
Just a guess but this plugin uses PHP sessions so that might be the cause.

Otherwise, these are the only two places I can see that modify headers within the plugin:

https://github.com/Florent73/send-pdf-for-contact-form-7/blob/f4d35e7fc42e9e3b80a34237e0e610eeac98c63f/classes/send-pdf.php#L38

The first has a conditional so should only happen on ?csv=1 (exporting csv?)

https://github.com/Florent73/send-pdf-for-contact-form-7/blob/f4d35e7fc42e9e3b80a34237e0e610eeac98c63f/classes/send-pdf.php#L88

The second should only happen when exporting settings.
